version: "3.5"

services:
  db:
    image: "postgres:14"
    container_name: geapPostreSQL
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "GEAPDB"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    build: 
      dockerfile: postgres.Dockerfile
      